### ISSUE TITLE
Add more context to the constrains?

### ISSUE THREAD

**Issue by tomaszpolanski** [thomasnield/optimized-scheduling-demo#1]
Thanks for the project, it's quite enlightening!

Would it be possible to add some more information about the constraints?
For example variables in `// 2 <= E - S` are not clear. 
It would be great for `ScheduleEntities.kt` have also similar descriptions as `Model.kt` (which is pretty clear).
Similar thing with `val discreteLength = (hoursLength * 4).toInt()` - what is `4` here?

Again, thanks for teaching us, normal developers, a more scientific approach to development!

**Comment by thomasnield** [comment]
Thanks @tomaszpolanski, glad you find this engaging. I'm actually posting examples [here](https://github.com/thomasnield/mathematical-optimization-examples) for this [book](https://www.amazon.com/gp/product/1118443330/) I'm reading and recommending to folks. 

I will see if I can improve the descriptions. One thing I'd like to see is [KotlinDocs support MathJax, which I filed a KEEP for](https://github.com/Kotlin/dokka/issues/245).  I know there is a way to do it now but it requires a lot of hacky build configuration.

**Comment by thomasnield** [comment]
I just overhauled this model and I got it working. I will document it more thoroughly in the coming week, and I'm also going to write a blog article about how I did this.

**Comment by tomaszpolanski** [comment]
Thanks for that! I hope the post will be as good as Linear Programming Part I

**Comment by thomasnield** [comment]
@tomaszpolanski it will be better. I've figured out some ways to simplify the problem greatly and make it perform faster.

**Comment by thomasnield** [comment]
Hopefully this is well-documented now. I even wrote a blog article about this. 
http://tomstechnicalblog.blogspot.com/2018/02/linear-programming-with-kotlin-part-iii.html
